import {
  mdiAccountCircle,
  mdiAlert,
  mdiArrowRight,
  mdiCheck,
  mdiChevronRight,
  mdiClose,
  mdiCloseCircle,
  mdiContentCopy,
  mdiDelete,
  mdiFlag,
  mdiHelpCircleOutline,
  mdiInformation,
  mdiMagnify,
  mdiMenu,
  mdiNumeric1Box,
  mdiNumeric2Box,
  mdiPin,
  mdiPinOutline,
  mdiPlus,
  mdiScissorsCutting,
  mdiTable,
  mdiViewDashboard,
  mdiWeatherNight,
  mdiWeatherSunny,
} from '@mdi/js';

export const ICONS = [
  { name: 'menu', path: mdiMenu },
  { name: 'alert', path: mdiAlert },
  { name: 'help-circle-outline', path: mdiHelpCircleOutline },
  { name: 'information', path: mdiInformation },
  { name: 'weather-night', path: mdiWeatherNight },
  { name: 'view-dashboard', path: mdiViewDashboard },
  { name: 'numeric-1-box', path: mdiNumeric1Box },
  { name: 'numeric-2-box', path: mdiNumeric2Box },
  { name: 'flag', path: mdiFlag },
  { name: 'check', path: mdiCheck },
  { name: 'close', path: mdiClose },
  { name: 'weather-sunny', path: mdiWeatherSunny },
  { name: 'table', path: mdiTable },
  { name: 'arrow-right', path: mdiArrowRight },
  { name: 'account-circle', path: mdiAccountCircle },
  { name: 'chevron-right', path: mdiChevronRight },
  { name: 'scissors-cutting', path: mdiScissorsCutting },
  { name: 'magnify', path: mdiMagnify },
  { name: 'plus', path: mdiPlus },
  { name: 'close-circle', path: mdiCloseCircle },
  { name: 'delete', path: mdiDelete },
  { name: 'pin', path: mdiPin },
  { name: 'pin-outline', path: mdiPinOutline },
  { name: 'content-copy', path: mdiContentCopy },
];
